language: node_js
node_js:
  - 10
script: "rake"
sudo: required
services:
 - docker

before_install:
 - npm install
 - docker build -t waqaransari/docker-react -f dockerfile.dev .

script:
 - docker run -e CI=true waqaransari/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-1-949832723040"
 bucket_path: "docker"
 on:
   branch: master

